/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/


const fibonacciSum = () => {
const arr = [1,2];
let sum = 0;
let i=1;
while(arr[i]<4000000) {
  arr.push(arr[i-1]+arr[i])
  i++
  }
let evenArr = arr.map(el => {
  if (el%2===0) {
    sum+=el
  }
})
return sum
}

fibonacciSum();
